name: Verify PR Title Format

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pr_name.outputs.version }}
      prefix: ${{ steps.pr_name.outputs.prefix }}
      prid: ${{ steps.pr_name.outputs.prid }}
    steps:
      - name: Verify Pull Request Title
        id: pr_name
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Pull Request title: ${PR_TITLE}"
          if [[ "$PR_TITLE" =~ ^([A-Z]{4})-([0-9]+) ]]; then
            prefix="${BASH_REMATCH[1]}"
            prid="${BASH_REMATCH[2]}"
            version="${BASH_REMATCH[0]}"
            echo "PR title format is valid."
            echo "::set-output name=prefix::$prefix"
            echo "::set-output name=prid::$prid"
            echo "::set-output name=version::$version"
          else
            echo "Error: PR title must start with a 4-letter prefix, a dash, and one or more digits (e.g. XXXX-12345)."
            exit 1
          fi
